version: '3.6'
services:
  py-http:
    build: .
    image: ${REPO:-duxing/datadog-otlp}:${TAG:-latest}
    command: ["opentelemetry-instrument", "flask", "run", "-h", "0.0.0.0", "-p", "8080"]
    environment:
      OTEL_SERVICE_NAME: my_service
      OTEL_RESOURCE_ATTRIBUTES: "service.name=my_service,deployment.environment=my_env,service.version=my_version"
      OTEL_EXPORTER_OTLP_ENDPOINT: datadog:4317
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: datadog:4317
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8080
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    ports:
      - 6379
  datadog:
    image: datadog/agent:7.35.0
    environment:
      # DD_LOG_LEVEL: trace
      DD_API_KEY: ${DD_API_KEY}
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: 0.0.0.0:4317
      DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_TRANSPORT: tcp
      DD_OTLP_CONFIG_METRICS_ENABLED: "true"
      DD_OTLP_CONFIG_TRACES_ENABLED: "true"
